apiVersion: v1
kind: Service
metadata:
  name: wisecow-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: wisecow
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30080

