name: CI/CD for Wisecow

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Login to Docker Hub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build & Push Docker Image
      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/wisecow:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/wisecow:latest

      # Step 4: Install kubectl
      - name: Install kubectl
        shell: bash
        run: |
          curl -LO "https://dl.k8s.io/release/v1.29.0/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/
          kubectl version --client

      # Step 5: Configure kubeconfig
      - name: Configure kubeconfig
        shell: bash
        run: |
          echo "${{ secrets.KUBECONFIG_DATA }}" | base64 --decode > kubeconfig
          mkdir -p $HOME/.kube
          mv kubeconfig $HOME/.kube/config
          chmod 600 $HOME/.kube/config
          kubectl config get-contexts
          
      # Step 6: Deploy to Kubernetes
      -  name: Deploy to Kubernetes
         shell: bash
         run: |
           NAMESPACE="default"

           echo "Checking k8s folder contents..."
           ls k8s/

           echo "Applying Deployment..."
           kubectl apply -f k8s/deployment.yaml -n $NAMESPACE

           sleep 5

           # Delete existing service if it exists
           if kubectl get svc wisecow-service -n $NAMESPACE > /dev/null 2>&1; then
           echo "Service exists. Deleting..."
           kubectl delete svc wisecow-service -n $NAMESPACE
           else
           echo "Service does not exist. Proceeding..."
           fi

           # Apply NodePort service
           echo "Applying Service..."
           kubectl apply -f k8s/service.yaml -n $NAMESPACE

           sleep 5

           # Verify service
           echo "Current Services:"
           kubectl get svc -n $NAMESPACE -o wide

           # Apply Ingress
           echo "Applying Ingress..."
           kubectl apply -f k8s/ingress.yaml -n $NAMESPACE