name: CI/CD for Wisecow

on:
  push:
    branches:
      - main   # Trigger when pushing to main

jobs:
  build-and-deploy:
    runs-on: self-hosted   # your Windows self-hosted runner

    steps:
    # Step 1: Checkout repo
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Login to Docker Hub
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 3: Build & Push Docker Image
    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/wisecow:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/wisecow:latest

    # Step 4: Install kubectl (Windows)
    - name: Install kubectl
      shell: powershell
      run: |
        Invoke-WebRequest -Uri https://dl.k8s.io/release/v1.29.0/bin/windows/amd64/kubectl.exe -OutFile kubectl.exe
        Move-Item -Path kubectl.exe -Destination "C:\Windows\System32\kubectl.exe" -Force
        kubectl version --client

    # Step 5: Configure kubeconfig from GitHub Secret (base64-decoded)
    - name: Configure kubeconfig
      shell: powershell
      run: |
        # Remove any line breaks or spaces from secret
        $b64 = "${{ secrets.KUBECONFIG_DATA }}" -replace "`r`n","" -replace "\s",""
        # Decode base64
        $decoded = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($b64))
        # Create .kube directory
        New-Item -ItemType Directory -Force -Path "$env:USERPROFILE\.kube"
        # Write decoded kubeconfig
        Set-Content -Path "$env:USERPROFILE\.kube\config" -Value $decoded

    # Step 6: Deploy to Kubernetes
    - name: Deploy to Kubernetes
      shell: powershell
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
        kubectl apply -f k8s/ingress.yaml
